"""
phase3_scenario_overlay_viewer.py

Standalone Streamlit viewer for the Phase 3B scenario-overlay output.

This viewer is intentionally separate from the main paid dashboard. It reads the
scenario overlay CSV and summary generated by:

    app/run_paid_simulator_phase3_scenario_overlay_check.py

The viewer is a visual inspection layer only. It does not promote the model and
it does not modify the customer-facing dashboard.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import Optional

import pandas as pd
import streamlit as st


CURRENT_FILE = Path(__file__).resolve()
PROJECT_ROOT = CURRENT_FILE.parents[2]
APP_DIR = PROJECT_ROOT / "app"
OUTPUT_TABLE_DIR = PROJECT_ROOT / "outputs" / "tables" / "paid_simulator"
OUTPUT_REPORT_DIR = PROJECT_ROOT / "outputs" / "reports" / "paid_simulator"

OVERLAY_CSV = OUTPUT_TABLE_DIR / "phase3_scenario_overlay.csv"
OVERLAY_HTML = OUTPUT_REPORT_DIR / "phase3_scenario_overlay.html"
OVERLAY_SUMMARY = OUTPUT_REPORT_DIR / "phase3_scenario_overlay_summary.txt"
SNAPSHOT_CSV = OUTPUT_TABLE_DIR / "phase3_interactive_payoff_snapshot.csv"
SNAPSHOT_HTML = OUTPUT_REPORT_DIR / "phase3_interactive_payoff_snapshot.html"
OVERLAY_CHECK = APP_DIR / "run_paid_simulator_phase3_scenario_overlay_check.py"


st.set_page_config(
    page_title="Phase 3B Scenario Overlay Viewer",
    layout="wide",
)


st.markdown(
    """
    <style>
        .block-container {
            max-width: 1220px;
            padding-top: 1.2rem;
            padding-bottom: 3rem;
        }
        .small-note {
            color: #666;
            font-size: 0.92rem;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


def read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except Exception as exc:  # pragma: no cover - defensive display only
        st.error(f"Could not read {path.name}: {exc}")
        return pd.DataFrame()


def read_text(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(errors="replace")
    except Exception as exc:  # pragma: no cover - defensive display only
        return f"Could not read {path.name}: {exc}"


def find_column(df: pd.DataFrame, candidates: list[str]) -> Optional[str]:
    lower_map = {str(col).strip().lower(): col for col in df.columns}
    for candidate in candidates:
        key = candidate.strip().lower()
        if key in lower_map:
            return lower_map[key]
    for candidate in candidates:
        key = candidate.strip().lower().replace("_", " ")
        for col in df.columns:
            normalized = str(col).strip().lower().replace("_", " ")
            if key == normalized:
                return col
    return None


def currency(value: object) -> str:
    try:
        number = float(value)
    except Exception:
        return "n/a"
    return f"${number:,.2f}"


def signed_currency(value: object) -> str:
    try:
        number = float(value)
    except Exception:
        return "n/a"
    sign = "+" if number >= 0 else "-"
    return f"{sign}${abs(number):,.2f}"


def run_overlay_check() -> tuple[int, str]:
    if not OVERLAY_CHECK.exists():
        return 1, f"Missing check script: {OVERLAY_CHECK}"
    try:
        result = subprocess.run(
            [sys.executable, str(OVERLAY_CHECK)],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            text=True,
            check=False,
        )
        output = (result.stdout or "") + ("\n" + result.stderr if result.stderr else "")
        return result.returncode, output.strip()
    except Exception as exc:  # pragma: no cover - defensive display only
        return 1, str(exc)


def show_file_status() -> None:
    rows = [
        ("Scenario-overlay CSV", OVERLAY_CSV),
        ("Scenario-overlay HTML", OVERLAY_HTML),
        ("Scenario-overlay summary", OVERLAY_SUMMARY),
        ("Interactive payoff snapshot CSV", SNAPSHOT_CSV),
        ("Interactive payoff snapshot HTML", SNAPSHOT_HTML),
        ("Scenario-overlay check script", OVERLAY_CHECK),
    ]
    status_df = pd.DataFrame(
        {
            "Item": [label for label, _ in rows],
            "Status": ["FOUND" if path.exists() else "MISSING" for _, path in rows],
            "Path": [str(path) for _, path in rows],
        }
    )
    st.dataframe(status_df, width="stretch", hide_index=True)


def show_metrics(df: pd.DataFrame) -> None:
    scenario_col = find_column(df, ["scenario", "scenario_name", "display_name", "scenario_label"])
    cc_col = find_column(df, ["covered_call_pl", "covered_call_p_l", "covered_call_profit_loss", "covered_call_pnl"])
    bh_col = find_column(df, ["buy_hold_pl", "buy_and_hold_pl", "buy_hold_p_l", "buy_hold_pnl"])
    rel_col = find_column(
        df,
        [
            "covered_call_minus_buy_hold",
            "covered_call_minus_buy_and_hold",
            "relative_result",
            "difference",
        ],
    )
    assignment_col = find_column(df, ["assignment_flag", "assigned", "assignment"])

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Scenarios", len(df))
    if rel_col is not None and not df.empty:
        c2.metric("Average relative result", signed_currency(pd.to_numeric(df[rel_col], errors="coerce").mean()))
        c3.metric("Best relative result", signed_currency(pd.to_numeric(df[rel_col], errors="coerce").max()))
        c4.metric("Worst relative result", signed_currency(pd.to_numeric(df[rel_col], errors="coerce").min()))
    else:
        c2.metric("Average relative result", "n/a")
        c3.metric("Best relative result", "n/a")
        c4.metric("Worst relative result", "n/a")

    if assignment_col is not None and not df.empty:
        st.caption(f"Assignment indicator column detected: `{assignment_col}`")

    if rel_col is not None and scenario_col is not None and not df.empty:
        chart_df = df[[scenario_col, rel_col]].copy()
        chart_df[rel_col] = pd.to_numeric(chart_df[rel_col], errors="coerce")
        chart_df = chart_df.dropna(subset=[rel_col])
        if not chart_df.empty:
            st.bar_chart(chart_df.set_index(scenario_col)[rel_col])

    if cc_col is not None and bh_col is not None and scenario_col is not None and not df.empty:
        line_df = df[[scenario_col, bh_col, cc_col]].copy()
        line_df[bh_col] = pd.to_numeric(line_df[bh_col], errors="coerce")
        line_df[cc_col] = pd.to_numeric(line_df[cc_col], errors="coerce")
        line_df = line_df.dropna(subset=[bh_col, cc_col])
        if not line_df.empty:
            st.line_chart(line_df.set_index(scenario_col)[[bh_col, cc_col]])


def show_snapshot(snapshot_df: pd.DataFrame) -> None:
    if snapshot_df.empty:
        st.info(
            "No interactive payoff snapshot has been saved yet. "
            "The scenario-overlay model can still run with its default SPY demo setup."
        )
        return
    st.dataframe(snapshot_df, width="stretch", hide_index=True)


def main() -> None:
    st.title("Phase 3B scenario-overlay viewer")
    st.caption(
        "Developer-only viewer for stress-testing the interactive covered-call payoff setup "
        "across simple price scenarios."
    )

    with st.sidebar:
        st.header("Phase 3B tools")
        if st.button("Run scenario-overlay check", use_container_width=True):
            code, output = run_overlay_check()
            if code == 0:
                st.success("Scenario-overlay check completed.")
            else:
                st.error("Scenario-overlay check returned a non-zero exit code.")
            with st.expander("Check output", expanded=True):
                st.code(output or "No output.")

        st.divider()
        st.caption("The saved payoff snapshot is optional. If missing, the overlay uses a default demo setup.")

    overlay_df = read_csv(OVERLAY_CSV)
    snapshot_df = read_csv(SNAPSHOT_CSV)
    summary_text = read_text(OVERLAY_SUMMARY)

    tab_overview, tab_overlay, tab_context, tab_files, tab_notes = st.tabs(
        ["Overview", "Scenario overlay", "Payoff context", "Files and reports", "Notes"]
    )

    with tab_overview:
        st.subheader("Overview")
        if overlay_df.empty:
            st.warning("No scenario-overlay CSV found yet. Run the scenario-overlay check first.")
            st.code(str(OVERLAY_CHECK))
        else:
            show_metrics(overlay_df)

        if summary_text:
            st.subheader("Scenario-overlay summary")
            st.text(summary_text)

    with tab_overlay:
        st.subheader("Scenario-overlay table")
        if overlay_df.empty:
            st.info("No scenario-overlay output is available yet.")
        else:
            st.dataframe(overlay_df, width="stretch", hide_index=True)

    with tab_context:
        st.subheader("Interactive payoff snapshot context")
        show_snapshot(snapshot_df)

    with tab_files:
        st.subheader("Files and reports")
        show_file_status()
        st.markdown("### Report paths")
        st.code(f"Scenario overlay HTML: {OVERLAY_HTML}")
        st.code(f"Scenario overlay summary: {OVERLAY_SUMMARY}")
        st.code(f"Interactive payoff snapshot CSV: {SNAPSHOT_CSV}")
        st.code(f"Interactive payoff snapshot HTML: {SNAPSHOT_HTML}")

    with tab_notes:
        st.subheader("Notes")
        st.markdown(
            """
            This is a developer inspection tool for Phase 3B. It is intended to answer:

            - How does the entered covered-call setup behave under simple price scenarios?
            - Where does the covered call beat or lag buy-and-hold?
            - Which scenarios create assignment risk?
            - Does the scenario overlay make the interactive payoff viewer more useful?

            This is still a modeled stress-test layer, not live market data and not a trade recommendation engine.
            """
        )


if __name__ == "__main__":
    main()
